In [ ]:
import pandas as pd

In [ ]:
df =pd.read_csv("/content/drive/MyDrive/dataset/medical_students_dataset.csv")

In [ ]:
df.head(20)

,Student ID,Age,Gender,Height,Weight,Blood Type,BMI,Temperature,Heart Rate,Blood Pressure,Cholesterol,Diabetes,Smoking
0,1.0,18.0,Female,161.777924,72.354947,O,27.645835,NaN,95.0,109.0,203.0,No,NaN
1,2.0,NaN,Male,152.069157,47.630941,B,NaN,98.714977,93.0,104.0,163.0,No,No
2,3.0,32.0,Female,182.537664,55.741083,A,16.729017,98.260293,76.0,130.0,216.0,Yes,No
3,NaN,30.0,Male,182.112867,63.332207,B,19.096042,98.839605,99.0,112.0,141.0,No,Yes
4,5.0,23.0,Female,NaN,46.234173,O,NaN,98.480008,95.0,NaN,231.0,No,No
5,6.0,32.0,NaN,151.491294,68.647805,B,29.912403,99.668373,70.0,128.0,183.0,NaN,Yes
6,7.0,21.0,NaN,172.949704,48.102744,AB,16.081635,97.715469,66.0,134.0,247.0,No,No
7,8.0,28.0,Male,186.489402,52.389752,AB,15.063921,98.227788,85.0,123.0,128.0,No,No
8,9.0,21.0,Male,155.039678,42.958703,B,NaN,98.808053,NaN,111.0,243.0,No,No
9,10.0,32.0,NaN,170.836315,50.783250,B,17.400435,98.570168,61.0,94.0,166.0,NaN,No
10,11.0,28.0,Female,152.973928,73.572814,B,31.440000,98.371843,60.0,NaN,241.0,No,Yes
11,12.0,34.0,Female,182.416302,76.371050,AB,22.950992,98.118274,86.0,97.0,247.0,No,No
12,13.0,29.0,Male,168.845992,48.533565,AB,NaN,98.515927,62.0,NaN,246.0,NaN,Yes
13,14.0,34.0,Male,NaN,60.882228,B,22.544095,98.963569,89.0,130.0,243.0,Yes,NaN
14,15.0,33.0,Male,184.718988,93.666944,NaN,27.451322,98.418213,68.0,133.0,180.0,Yes,Yes
15,NaN,21.0,Male,162.819718,96.385698,B,NaN,98.108563,68.0,126.0,130.0,No,No
16,17.0,24.0,Male,162.727013,86.228727,B,32.563619,98.057822,63.0,135.0,197.0,NaN,No
17,18.0,27.0,NaN,176.694741,56.243559,O,18.014638,NaN,78.0,NaN,161.0,No,No
18,19.0,31.0,Female,158.790160,46.829849,AB,18.572723,98.784709,92.0,102.0,172.0,NaN,No
19,20.0,31.0,Male,166.489929,49.955569,B,18.022207,98.809750,82.0,96.0,223.0,No,No

In [ ]:
df.shape

(200000, 13)

In [ ]:
df = df.drop_duplicates()
df.shape

(192356, 13)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 192356 entries, 0 to 199999
Data columns (total 13 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   Student ID      172465 non-null  float64
 1   Age             172464 non-null  float64
 2   Gender          172432 non-null  object
 3   Height          172449 non-null  float64
 4   Weight          172455 non-null  float64
 5   Blood Type      172440 non-null  object
 6   BMI             172456 non-null  float64
 7   Temperature     172445 non-null  float64
 8   Heart Rate      172453 non-null  float64
 9   Blood Pressure  172464 non-null  float64
 10  Cholesterol     172463 non-null  float64
 11  Diabetes        172451 non-null  object
 12  Smoking         172459 non-null  object
dtypes: float64(9), object(4)
memory usage: 20.5+ MB

identify column with missinf (null) values

In [ ]:
df.index

Index([     0,      1,      2,      3,      4,      5,      6,      7,      8,
            9,
       ...
       199990, 199991, 199992, 199993, 199994, 199995, 199996, 199997, 199998,
       199999],
      dtype='int64', length=192356)

In [ ]:
print(df.nunique())

Student ID        98976
Age                  17
Gender                2
Height            98992
Weight            99026
Blood Type            4
BMI               98983
Temperature       99006
Heart Rate           40
Blood Pressure       50
Cholesterol         130
Diabetes              2
Smoking               2
dtype: int64

In [ ]:
df.fillna('')

,Student ID,Age,Gender,Height,Weight,Blood Type,BMI,Temperature,Heart Rate,Blood Pressure,Cholesterol,Diabetes,Smoking
0,1.0,18.0,Female,161.777924,72.354947,O,27.645835,,95.0,109.0,203.0,No,
1,2.0,,Male,152.069157,47.630941,B,,98.714977,93.0,104.0,163.0,No,No
2,3.0,32.0,Female,182.537664,55.741083,A,16.729017,98.260293,76.0,130.0,216.0,Yes,No
3,,30.0,Male,182.112867,63.332207,B,19.096042,98.839605,99.0,112.0,141.0,No,Yes
4,5.0,23.0,Female,,46.234173,O,,98.480008,95.0,,231.0,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...
199995,,24.0,Male,176.50326,95.756997,B,30.737254,99.170685,65.0,121.0,130.0,No,No
199996,99997.0,29.0,Female,163.917675,45.225194,,16.831734,97.865785,62.0,125.0,198.0,No,Yes
199997,99998.0,34.0,Female,,99.648914,,33.189303,98.76821,60.0,90.0,154.0,,No
199998,99999.0,30.0,Female,156.446944,50.142824,A,20.486823,98.994212,61.0,106.0,225.0,No,No
199999,100000.0,20.0,Female,153.927409,99.928405,O,42.175189,98.595817,95.0,133.0,132.0,,No

In [ ]:
null_values = df.isnull().sum()
print(null_values [null_values > 0])

Student ID        19891
Age               19892
Gender            19924
Height            19907
Weight            19901
Blood Type        19916
BMI               19900
Temperature       19911
Heart Rate        19903
Blood Pressure    19892
Cholesterol       19893
Diabetes          19905
Smoking           19897
dtype: int64

In [ ]:
if 'Age' in df.columns:
  df.loc[:,'Age']= df['Age'].fillna(df['Age'].mean())

In [ ]:
if 'Height' in df.columns:
  df.loc[:,'Height']= df['Height'].fillna(df['Height'].mean())

In [ ]:
df.head()

,Student ID,Age,Gender,Height,Weight,Blood Type,BMI,Temperature,Heart Rate,Blood Pressure,Cholesterol,Diabetes,Smoking
0,1.0,18.000000,Female,161.777924,72.354947,O,27.645835,NaN,95.0,109.0,203.0,No,NaN
1,2.0,26.022254,Male,152.069157,47.630941,B,NaN,98.714977,93.0,104.0,163.0,No,No
2,3.0,32.000000,Female,182.537664,55.741083,A,16.729017,98.260293,76.0,130.0,216.0,Yes,No
3,NaN,30.000000,Male,182.112867,63.332207,B,19.096042,98.839605,99.0,112.0,141.0,No,Yes
4,5.0,23.000000,Female,174.958363,46.234173,O,NaN,98.480008,95.0,NaN,231.0,No,No

In [ ]:
if 'Weight' in df.columns:
  df.loc[:,'Weight']= df['Weight'].fillna(df['Weight'].mean())

In [ ]:
if 'BMI' in df.columns:
  df.loc[:,'BMI']= df['BMI'].fillna(df['BMI'].mean())

In [ ]:
if 'Temperature' in df.columns:
  df.loc[:,'Temperature']= df['Temperature'].fillna(df['Temperature'].mean())

In [ ]:
df = df.rename(columns = {'Heart Rate' : 'Heart_Rate' , 'Blood Pressure ' : 'Blood_Pressure' , 'Blood Type ' : 'Blood_Type'})

In [ ]:
df.columns

Index(['Student ID', 'Age', 'Gender', 'Height', 'Weight', 'Blood Type', 'BMI',
       'Temperature', 'Heart_Rate', 'Blood Pressure', 'Cholesterol',
       'Diabetes', 'Smoking'],
      dtype='object')

In [ ]:
if 'Heart_Rate' in df.columns:
  df.loc[:, 'Heart_Rate']=df['Heart_Rate'].fillna(df['Heart_Rate'].mean())

In [ ]:
if 'Blood_Pressure' in df.columns:
  df.loc[:, 'Blood_Pressure']=df['Blood_Pressure'].fillna(df['Blood_Pressure'].mean())

In [ ]:
if 'Cholesterol' in df.columns:
  df.loc[:, 'Cholesterol']=df['Cholesterol'].fillna(df['Cholesterol'].mean())

In [ ]:
if'Cholesterol' in df.columns:
  df.loc[:, 'Cholesterol']=df['Cholesterol'].fillna(df['Cholesterol'].mean())

In [ ]:
if 'Diabetes' in df.columns:
  df.loc[:, 'Diabetes']=df['Diabetes'].fillna(df['Diabetes'].mode()[0])

In [ ]:
df.head()

,Student ID,Age,Gender,Height,Weight,Blood Type,BMI,Temperature,Heart_Rate,Blood Pressure,Cholesterol,Diabetes,Smoking
0,1.0,18.000000,Female,161.777924,72.354947,O,27.645835,98.601117,95.0,109.0,203.0,No,NaN
1,2.0,26.022254,Male,152.069157,47.630941,B,23.338982,98.714977,93.0,104.0,163.0,No,No
2,3.0,32.000000,Female,182.537664,55.741083,A,16.729017,98.260293,76.0,130.0,216.0,Yes,No
3,NaN,30.000000,Male,182.112867,63.332207,B,19.096042,98.839605,99.0,112.0,141.0,No,Yes
4,5.0,23.000000,Female,174.958363,46.234173,O,23.338982,98.480008,95.0,NaN,231.0,No,No

In [ ]:
null_values_after_correction = df.isnull().sum()

In [ ]:
print(null_values_after_correction)

Student ID        19891
Age                   0
Gender            19924
Height                0
Weight                0
Blood Type        19916
BMI                   0
Temperature           0
Heart_Rate            0
Blood Pressure    19892
Cholesterol           0
Diabetes              0
Smoking           19897
dtype: int64

In [ ]:
df.head()

,Student ID,Age,Gender,Height,Weight,Blood Type,BMI,Temperature,Heart_Rate,Blood Pressure,Cholesterol,Diabetes,Smoking
0,1.0,18.000000,Female,161.777924,72.354947,O,27.645835,98.601117,95.0,109.0,203.0,No,NaN
1,2.0,26.022254,Male,152.069157,47.630941,B,23.338982,98.714977,93.0,104.0,163.0,No,No
2,3.0,32.000000,Female,182.537664,55.741083,A,16.729017,98.260293,76.0,130.0,216.0,Yes,No
3,NaN,30.000000,Male,182.112867,63.332207,B,19.096042,98.839605,99.0,112.0,141.0,No,Yes
4,5.0,23.000000,Female,174.958363,46.234173,O,23.338982,98.480008,95.0,NaN,231.0,No,No

In [ ]:
null_values_after_correction = df.isnull().sum()

In [ ]:
df =df.rename(columns={'Student_Id' : 'Student_Id'})

In [ ]:
if 'Student_Id' in df.columns:
  df.loc[:, 'Student_Id']= range(1,len(df)+1)

In [ ]:
df.head(10)

,Student ID,Age,Gender,Height,Weight,Blood Type,BMI,Temperature,Heart_Rate,Blood Pressure,Cholesterol,Diabetes,Smoking
0,1.0,18.000000,Female,161.777924,72.354947,O,27.645835,98.601117,95.000000,109.0,203.0,No,NaN
1,2.0,26.022254,Male,152.069157,47.630941,B,23.338982,98.714977,93.000000,104.0,163.0,No,No
2,3.0,32.000000,Female,182.537664,55.741083,A,16.729017,98.260293,76.000000,130.0,216.0,Yes,No
3,NaN,30.000000,Male,182.112867,63.332207,B,19.096042,98.839605,99.000000,112.0,141.0,No,Yes
4,5.0,23.000000,Female,174.958363,46.234173,O,23.338982,98.480008,95.000000,NaN,231.0,No,No
5,6.0,32.000000,NaN,151.491294,68.647805,B,29.912403,99.668373,70.000000,128.0,183.0,No,Yes
6,7.0,21.000000,NaN,172.949704,48.102744,AB,16.081635,97.715469,66.000000,134.0,247.0,No,No
7,8.0,28.000000,Male,186.489402,52.389752,AB,15.063921,98.227788,85.000000,123.0,128.0,No,No
8,9.0,21.000000,Male,155.039678,42.958703,B,23.338982,98.808053,79.508817,111.0,243.0,No,No
9,10.0,32.000000,NaN,170.836315,50.783250,B,17.400435,98.570168,61.000000,94.0,166.0,No,No

In [ ]:
null_values_after_correction = df.isnull().sum()
null_values_after_correction

Student ID        19891
Age                   0
Gender            19924
Height                0
Weight                0
Blood Type        19916
BMI                   0
Temperature           0
Heart_Rate            0
Blood Pressure    19892
Cholesterol           0
Diabetes              0
Smoking           19897
dtype: int64

In [ ]:
df

,Student ID,Age,Gender,Height,Weight,Blood Type,BMI,Temperature,Heart_Rate,Blood Pressure,Cholesterol,Diabetes,Smoking
0,1.0,18.000000,Female,161.777924,72.354947,O,27.645835,98.601117,95.0,109.0,203.0,No,NaN
1,2.0,26.022254,Male,152.069157,47.630941,B,23.338982,98.714977,93.0,104.0,163.0,No,No
2,3.0,32.000000,Female,182.537664,55.741083,A,16.729017,98.260293,76.0,130.0,216.0,Yes,No
3,NaN,30.000000,Male,182.112867,63.332207,B,19.096042,98.839605,99.0,112.0,141.0,No,Yes
4,5.0,23.000000,Female,174.958363,46.234173,O,23.338982,98.480008,95.0,NaN,231.0,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...
199995,NaN,24.000000,Male,176.503260,95.756997,B,30.737254,99.170685,65.0,121.0,130.0,No,No
199996,99997.0,29.000000,Female,163.917675,45.225194,NaN,16.831734,97.865785,62.0,125.0,198.0,No,Yes
199997,99998.0,34.000000,Female,174.958363,99.648914,NaN,33.189303,98.768210,60.0,90.0,154.0,No,No
199998,99999.0,30.000000,Female,156.446944,50.142824,A,20.486823,98.994212,61.0,106.0,225.0,No,No
199999,100000.0,20.000000,Female,153.927409,99.928405,O,42.175189,98.595817,95.0,133.0,132.0,No,No

In [ ]:
df = df.drop(co;umns=['Gender'])

In [ ]:
df = df.drop(columns=['Blood Type'])

In [ ]:
df

,Student ID,Age,Height,Weight,BMI,Temperature,Heart_Rate,Blood Pressure,Cholesterol,Diabetes,Smoking
0,1.0,18.000000,161.777924,72.354947,27.645835,98.601117,95.0,109.0,203.0,No,NaN
1,2.0,26.022254,152.069157,47.630941,23.338982,98.714977,93.0,104.0,163.0,No,No
2,3.0,32.000000,182.537664,55.741083,16.729017,98.260293,76.0,130.0,216.0,Yes,No
3,NaN,30.000000,182.112867,63.332207,19.096042,98.839605,99.0,112.0,141.0,No,Yes
4,5.0,23.000000,174.958363,46.234173,23.338982,98.480008,95.0,NaN,231.0,No,No
...,...,...,...,...,...,...,...,...,...,...,...
199995,NaN,24.000000,176.503260,95.756997,30.737254,99.170685,65.0,121.0,130.0,No,No
199996,99997.0,29.000000,163.917675,45.225194,16.831734,97.865785,62.0,125.0,198.0,No,Yes
199997,99998.0,34.000000,174.958363,99.648914,33.189303,98.768210,60.0,90.0,154.0,No,No
199998,99999.0,30.000000,156.446944,50.142824,20.486823,98.994212,61.0,106.0,225.0,No,No
199999,100000.0,20.000000,153.927409,99.928405,42.175189,98.595817,95.0,133.0,132.0,No,No

In [ ]:
df.shape

(192356, 13)

In [ ]:
null_values_after_correction_final=df.isnull().sum()
null_values_after_correction_final

Student ID        19891
Age                   0
Height                0
Weight                0
BMI                   0
Temperature           0
Heart_Rate            0
Blood Pressure    19892
Cholesterol           0
Diabetes              0
Smoking           19897
dtype: int64

In [ ]:
df.head(30)

,Student ID,Age,Height,Weight,BMI,Temperature,Heart_Rate,Blood Pressure,Cholesterol,Diabetes,Smoking
0,1.0,18.000000,161.777924,72.354947,27.645835,98.601117,95.000000,109.0,203.000000,No,NaN
1,2.0,26.022254,152.069157,47.630941,23.338982,98.714977,93.000000,104.0,163.000000,No,No
2,3.0,32.000000,182.537664,55.741083,16.729017,98.260293,76.000000,130.0,216.000000,Yes,No
3,NaN,30.000000,182.112867,63.332207,19.096042,98.839605,99.000000,112.0,141.000000,No,Yes
4,5.0,23.000000,174.958363,46.234173,23.338982,98.480008,95.000000,NaN,231.000000,No,No
5,6.0,32.000000,151.491294,68.647805,29.912403,99.668373,70.000000,128.0,183.000000,No,Yes
6,7.0,21.000000,172.949704,48.102744,16.081635,97.715469,66.000000,134.0,247.000000,No,No
7,8.0,28.000000,186.489402,52.389752,15.063921,98.227788,85.000000,123.0,128.000000,No,No
8,9.0,21.000000,155.039678,42.958703,23.338982,98.808053,79.508817,111.0,243.000000,No,No
9,10.0,32.000000,170.836315,50.783250,17.400435,98.570168,61.000000,94.0,166.000000,No,No
10,11.0,28.000000,152.973928,73.572814,31.440000,98.371843,60.000000,NaN,241.000000,No,Yes
11,12.0,34.000000,182.416302,76.371050,22.950992,98.118274,86.000000,97.0,247.000000,No,No
12,13.0,29.000000,168.845992,48.533565,23.338982,98.515927,62.000000,NaN,246.000000,No,Yes
13,14.0,34.000000,174.958363,60.882228,22.544095,98.963569,89.000000,130.0,243.000000,Yes,NaN
14,15.0,33.000000,184.718988,93.666944,27.451322,98.418213,68.000000,133.0,180.000000,Yes,Yes
15,NaN,21.000000,162.819718,96.385698,23.338982,98.108563,68.000000,126.0,130.000000,No,No
16,17.0,24.000000,162.727013,86.228727,32.563619,98.057822,63.000000,135.0,197.000000,No,No
17,18.0,27.000000,176.694741,56.243559,18.014638,98.601117,78.000000,NaN,161.000000,No,No
18,19.0,31.000000,158.790160,46.829849,18.572723,98.784709,92.000000,102.0,172.000000,No,No
19,20.0,31.000000,166.489929,49.955569,18.022207,98.809750,82.000000,96.0,223.000000,No,No
20,21.0,30.000000,180.913766,72.193659,23.338982,98.910825,95.000000,101.0,176.000000,No,No
21,22.0,22.000000,189.082136,83.536602,23.365539,99.385818,64.000000,124.0,184.499765,No,Yes
22,23.0,29.000000,179.909041,90.679436,28.015787,98.782269,81.000000,108.0,227.000000,No,Yes
23,24.0,18.000000,174.958363,52.521560,13.570402,98.215090,60.000000,132.0,217.000000,No,No
24,25.0,27.000000,187.411623,81.219470,23.124221,97.738939,99.000000,135.0,123.000000,No,No
25,26.0,28.000000,183.519003,61.080100,18.135839,98.623771,96.000000,101.0,147.000000,No,NaN
26,27.0,29.000000,173.018801,44.032057,14.708974,98.855958,98.000000,115.0,219.000000,No,NaN
27,28.0,24.000000,187.777839,40.485525,11.481830,98.883412,61.000000,95.0,242.000000,No,Yes
28,29.0,26.022254,174.958363,82.826786,32.276465,98.601117,60.000000,93.0,184.499765,No,NaN
29,30.0,34.000000,192.499119,86.907744,23.453139,99.469634,68.000000,124.0,165.000000,No,No

In [ ]:
df.duplicated().sum()

5934

In [ ]:
df.describe()

,Student ID,Age,Height,Weight,BMI,Temperature,Heart_Rate,Blood Pressure,Cholesterol
count,172465.000000,192356.000000,192356.000000,192356.000000,192356.000000,192356.000000,192356.000000,172464.000000,192356.000000
mean,49981.974488,26.022254,174.958363,69.980827,23.338982,98.601117,79.508817,114.564761,184.499765
std,28886.214693,4.630816,13.683044,16.403026,6.659926,0.473620,10.929640,14.404302,35.556334
min,1.000000,18.000000,150.000041,40.000578,10.074837,96.397835,60.000000,90.000000,120.000000
25%,24968.000000,22.000000,163.928160,56.696915,18.404855,98.308410,71.000000,102.000000,156.000000
50%,49950.000000,26.022254,174.958363,69.980827,23.338982,98.601117,79.508817,115.000000,184.499765
75%,75015.000000,30.000000,186.032826,83.262503,27.231679,98.895268,88.000000,127.000000,213.000000
max,100000.000000,34.000000,199.998639,99.999907,44.355113,100.824857,99.000000,139.000000,249.000000